// This file is part of GQCG-GQCP.
//
// Copyright (C) 2017-2020  the GQCG developers
//
// GQCG-GQCP is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// GQCG-GQCP is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with GQCG-GQCP.  If not, see <http://www.gnu.org/licenses/>.

#include "Basis/ScalarBasis/GTOShell.hpp"
#include "Basis/SpinorBasis/GSpinorBasis.hpp"
#include "Molecule/Molecule.hpp"
#include "Operator/FirstQuantized/Operator.hpp"
#include "gqcpy/include/interfaces.hpp"

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>


namespace py = pybind11;


namespace gqcpy {


// Provide some shortcuts for frequent namespaces.
namespace py = pybind11;
using namespace GQCP;


/**
 *  Add Python bindings for some APIs related to `GSpinorBasis`.
 * 
 *  @tparam Class               The type of the Pybind11 `class_` (generated by the compiler).
 *  
 *  @param py_class             The Pybind11 `class_` that should obtain APIs related to `GSpinorBasis`.
 */
template <typename Class>
void bindGSpinorBasisInterface(Class& py_class) {

    // The C++ type corresponding to the Python class.
    using Type = typename Class::type;
    using Scalar = typename Type::ExpansionScalar;


    /*
     *  MARK: Constructors
     */

    py_class
        .def(py::init<const Molecule&, const std::string&>(),
             py::arg("molecule"),
             py::arg("basisset_name"));


    /*
     *  MARK: Named constructors
     */

    py_class
        .def_static("FromRestricted",
                    [](const RSpinOrbitalBasis<Scalar, GTOShell>& r_spinor_basis) {
                        return Type::FromRestricted(r_spinor_basis);
                    });


    /*
     *  MARK: Coefficients
     */

    py_class
        .def(
            "numberOfCoefficients",
            &Type::numberOfCoefficients,
            py::arg("sigma"),
            "Return the number of coefficients that are used for the expansion of the requested spin-component of a spinor");


    // Expose the `SimpleSpinorBasis` API to the Python class.
    bindSpinorBasisInterface(py_class);


    /*
     *  MARK: General info
     */

    py_class
        .def(
            "numberOfSpinors",
            &Type::numberOfSpinors,
            "The number of spinors that are described by this generalized spinor basis.");


    // Expose some quantization API to the Python class;
    bindSpinorBasisQuantizationInterface(py_class);


    // Expose some Mulliken API to the Python class;
    bindSpinorBasisMullikenInterface(py_class);
}


/**
 *  Register `GSpinorBasis_d` and `GSpinorBasis_cd` to the gqcpy module and expose parts of their C++ interfaces to Python.
 * 
 *  @param module           The Pybind11 module in which the classes should be registered.
 */
void bindGSpinorBases(py::module& module) {

    // Define the Python class for `GSpinorBasis_d`.
    py::class_<GSpinorBasis<double, GTOShell>> py_GSpinorBasis_d {module, "GSpinorBasis_d", "A class that represents a real, (generalized) spinor basis with underlying GTO shells."};

    bindGSpinorBasisInterface(py_GSpinorBasis_d);


    // Define the Python class for `GSpinorBasis_cd`.
    py::class_<GSpinorBasis<complex, GTOShell>> py_GSpinorBasis_cd {module, "GSpinorBasis_cd", "A class that represents a complex, (generalized) spinor basis with underlying GTO shells."};

    bindGSpinorBasisInterface(py_GSpinorBasis_cd);
}


}  // namespace gqcpy
