# Specify the virtual environment
dist: bionic
sudo: true

# Specify the project language and the compiler to test to
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

# Enable Slack notifications, disable e-mail
notifications:
    slack: GQCG:5PZ5ibXCwNU1b5ToWbHVIqnI
    email: false

before_cache:
    - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
    - pip uninstall -y cardboardlint

# Cache miniconda for faster build procedures
cache:
    directories:
        - $HOME/miniconda
        - $HOME/download

before_install:
    # Install Miniconda
    - if [ -d $HOME/miniconda/bin ]; then
        echo "Miniconda already installed.";
      else
        echo "Installing miniconda.";
        rm -rf $HOME/miniconda;
        mkdir -p $HOME/download;
        if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
            wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
        else
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
        fi;
        bash $HOME/download/miniconda.sh -b -p ${HOME}/miniconda;
      fi

    # Set GCC 8 compiler
    - export CC=/usr/bin/gcc-8
    - export CXX=/usr/bin/g++-8

# Install general dependencies
install:

    # Configure conda
    - source $HOME/miniconda/bin/activate
    - hash -r
    - conda config --set always_yes yes --set changeps1 no

    # Install a recent version of CMake, Boost and eigen if they are not yet already installed.
    - if [ ! -f $HOME/miniconda/bin/cmake ]; then
        conda install -c conda-forge openmp=8.0.1 cmake=3.13 boost-cpp=1.69.0 eigen=3.3.7 blas=2.15 mkl=2019.0 pybind11=2.4.3 benchmark numpy=1.18.1;
        conda install -c gqcg libint=2.3.1 cint=3.0.17;
        conda install -c intel mkl-include=2019.0 mkl-static=2019.0 intel-openmp=2019.0;
      else
        echo "Using already installed packages.";
      fi
    - export PATH=${HOME}/miniconda/bin:${PATH} # Use conda CMake
    - export LIBINT_DATA_PATH=${HOME}/miniconda/share/libint/2.3.1/basis

# Run the build script
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DBUILD_TESTS=TRUE -DBUILD_BENCHMARKS=TRUE -DBUILD_PYTHON_BINDINGS=TRUE -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_PREFIX_PATH=${HOME}/miniconda
  - make -j3 VERBOSE=1 && env CTEST_OUTPUT_ON_FAILURE=1 make test ARGS=-j3 && sudo make install

# Run the benchmarks
  - cd gqcp/benchmarks
  - ./doci_case --benchmark_counters_tabular=true
  - ./doci_matrix --benchmark_counters_tabular=true
  - ./doci_matvec --benchmark_counters_tabular=true
  - ./fci_matrix --benchmark_counters_tabular=true
  - ./fci_matvec --benchmark_counters_tabular=true
  - ./hubbard_diagonalization --benchmark_counters_tabular=true
  - ./hubbard_matrix --benchmark_counters_tabular=true
  - ./hubbard_matvec --benchmark_counters_tabular=true

# Test if installed library links properly to external driver
  - cd /tmp
  - git clone https://github.com/GQCG/gqcp-link.git
  - cd gqcp-link
  - mkdir build && cd build
  - cmake .. -DCMAKE_PREFIX_PATH=${HOME}/miniconda -DGQCP_INSTALL_PREFIX=~/.local
  - make -j3 && ./test_driver
