# Specify the virtual environment
dist: trusty
sudo: true

# Specify the project language and the compiler to test to
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

# Enable Slack notifications, disable e-mail
notifications:
    slack: GQCG:5PZ5ibXCwNU1b5ToWbHVIqnI
    email: false

before_cache:
    - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
    - pip uninstall -y cardboardlint

# Cache miniconda for faster build procedures
cache:
    directories:
        - $HOME/miniconda
        - $HOME/download

before_install:
    # Install Miniconda
    - if [ -d $HOME/miniconda/bin ]; then
        echo "Miniconda already installed.";
      else
        echo "Installing miniconda.";
        rm -rf $HOME/miniconda;
        mkdir -p $HOME/download;
        if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
            wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
        else
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
        fi;
        bash $HOME/download/miniconda.sh -b -p ${HOME}/miniconda;
      fi

    # Add headers and libraries to path
    - export CONDA_HOME=${HOME}/miniconda
    - export C_INCLUDE_PATH=${CONDA_HOME}/include:${C_INCLUDE_PATH}
    - export CPLUS_INCLUDE_PATH=${CONDA_HOME}/include:${CPLUS_INCLUDE_PATH}
    - export LIBRARY_PATH=${CONDA_HOME}/lib:${LIBRARY_PATH}
    - export LD_LIBRARY_PATH=${CONDA_HOME}/lib:${LD_LIBRARY_PATH}
    - export DYLD_FALLBACK_LIBRARY_PATH=${CONDA_HOME}/lib:${DYLD_FALLBACK_LIBRARY_PATH}

    # Set GCC 7 compiler
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - gcc -v && g++ -v && cmake --version

# Install general dependencies
install:

    # Configure conda
    - source $HOME/miniconda/bin/activate
    - hash -r
    - conda config --set always_yes yes --set changeps1 no

    # Install a recent version of CMake, Boost and eigen if they are not yet already installed.
    - if [ ! -f $HOME/miniconda/bin/cmake ]; then
        conda install -c conda-forge cmake boost boost-cpp eigen;
        conda install -c gqcg libint;
      else
        echo "Using already installed packages.";
      fi
    - export BOOST_ROOT=${HOME}/miniconda/include
    - export LIBINT_DATA_PATH=${HOME}/miniconda/share/libint/2.3.1/basis

    # Install google benchmark
    - mkdir /tmp/bench && cd /tmp/bench
    # Fork from tmhuysen for cmake fix
    - git clone https://github.com/tmhuysen/benchmark.git
    # Benchmark requires Google Test as a dependency. Add the source tree as a subdirectory.
    - cd benchmark
    - git clone https://github.com/google/googletest.git
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=RELEASE
    - make -j3 && sudo make install

# Run the build script
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DBUILD_BENCHMARKS=ON
  - make -j3 VERBOSE=1 && make test ARGS=-j3 && sudo make install

# Run the benchmarks
  - cd benchmarks
  - ./doci_case --benchmark_counters_tabular=true
  - ./doci_matrix --benchmark_counters_tabular=true
  - ./doci_matvec --benchmark_counters_tabular=true
  - ./fci_matrix --benchmark_counters_tabular=true
  - ./fci_matvec --benchmark_counters_tabular=true
  - ./hubbard_diagonalization --benchmark_counters_tabular=true
  - ./hubbard_matrix --benchmark_counters_tabular=true
  - ./hubbard_matvec --benchmark_counters_tabular=true
