name: gqcp_dev
channels:
  - intel
  - gqcg
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cmake=3.13 
  - boost-cpp=1.69.0 
  - eigen=3.3.7 
  - blas=2.15 
  - mkl=2019.0 
  - pybind11=2.4.3 
  - benchmark 
  - numpy=1.18.1
  - libint=2.3.1 
  - cint=3.0.17
  - mkl-include=2019.0 
  - mkl-static=2019.0 
  - intel-openmp=2019.0
  - nodejs
  - python=3.8
  - notebook=6.1.1
