// This file is part of GQCG-GQCP.
//
// Copyright (C) 2017-2020  the GQCG developers
//
// GQCG-GQCP is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// GQCG-GQCP is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with GQCG-GQCP.  If not, see <http://www.gnu.org/licenses/>.

#include "Mathematical/Algorithm/IterativeAlgorithm.hpp"
#include "QCMethod/HF/UHF/UHF.hpp"
#include "QCMethod/HF/UHF/UHFSCFSolver.hpp"
#include "Utilities/aliases.hpp"

#include <pybind11/pybind11.h>


namespace gqcpy {


// Provide some shortcuts for frequent namespaces.
namespace py = pybind11;
using namespace GQCP;


/**
 *  Add Python bindings for some APIs related to `QCMethod::UHF`.
 * 
 *  @tparam Class               The type of the Pybind11 `class_` (generated by the compiler).
 *  
 *  @param py_class             The Pybind11 `class_` that should obtain APIs related to `QCMethod::UHF`.
 */
template <typename Class>
void bindQCMethodUHFInterface(Class& py_class) {

    // The C++ type corresponding to the Python class.
    using Type = typename Class::type;
    using Scalar = typename Type::Scalar;


    py_class

        /*
         *  MARK: Public methods
         */

        .def_static(
            "optimize",
            [](IterativeAlgorithm<UHFSCFEnvironment<Scalar>>& solver, UHFSCFEnvironment<Scalar>& environment) {
                return QCMethod::UHF<Scalar>().optimize(solver, environment);
            },
            py::arg("solver"),
            py::arg("environment"),
            "Optimize the UHF wave function model.");
}


/**
 *  Add Python bindings for UHF QCMethods.
 */
void bindQCMethodsUHF(py::module& module) {

    // Provide Python bindings for real-valued UHF.
    py::class_<QCMethod::UHF<double>> py_QCMethodUHF_d {module, "UHF_d", "The (real) unrestricted Hartree-Fock quantum chemical method."};

    bindQCMethodUHFInterface(py_QCMethodUHF_d);


    // Provide Python bindings for complex-valued UHF.
    py::class_<QCMethod::UHF<complex>> py_QCMethodUHF_cd {module, "UHF_cd", "The (complex) unrestricted Hartree-Fock quantum chemical method."};

    bindQCMethodUHFInterface(py_QCMethodUHF_cd);
}


}  // namespace gqcpy
