// This file is part of GQCG-GQCP.
//
// Copyright (C) 2017-2020  the GQCG developers
//
// GQCG-GQCP is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// GQCG-GQCP is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with GQCG-GQCP.  If not, see <http://www.gnu.org/licenses/>.

#include "Partition/ONVPartition.hpp"
#include "gqcpy/include/interfaces.hpp"

#include <pybind11/pybind11.h>


namespace gqcpy {


// Provide some shortcuts for frequent namespaces.
namespace py = pybind11;
using namespace GQCP;


/**
 *  Register `ONVPartition` to the gqcpy module and expose a part of its C++ interface to Python.
 *
 *  @tparam Class               The type of the Pybind11 `class_` (generated by the compiler).
 *
 *  @param py_class             The Pybind11 `class_` that should obtain APIs related to `ONVPartition`.
 */
template <typename Class>
void bindONVPartitionInterface(Class& py_class) {

    // The C++ type corresponding to the Python class.
    using Type = typename Class::type;

    // Expose python bindings unique to the ONV partition.
    module

        /*
         *  MARK: Constructors
         */

        .def(py::init<const DiscreteDomainPartition&, const SpinUnresolvedONV&>(),
             py::arg("domain_partition"),
             py::arg("onv"))

        .def(py::init<const DiscreteDomainPartition&, const SpinResolvedONV&>(),
             py::arg("domain_partition"),
             py::arg("onv"))

        /*
         *  MARK: General info
         */

        .def(
            "asString",
            &ONVPartition<Type>::asString)

        .def(
            "phaseFactor",
            &ONVPartition<Type>::phaseFactor);


    // Expose the `SimplePartition` interfaces to the Python class.
    bindSimplePartitionInterface(module);
}


/**
 *  Register multiple templated `ONVPartition` to the gqcpy module and expose parts of their C++ interfaces to Python.
 *
 *  @param module           The Pybind11 module in which the classes should be registered.
 */
void bindONVPartition(py::module& module) {

    bindONVPartitionInterface<SpinResolvedONV>(module);
    bindONVPartitionInterface<SpinUnresolvedONV>(module);
}


}  // namespace gqcpy
