c_compiler:
  - clang                         # [osx]
  - gcc                           # [linux]
cxx_compiler:
  - clangxx                       # [osx]
  - gxx                           # [linux]
fortran_compiler:
  - gfortran
target_platform:
  - osx-64                        # [osx]
  - linux-64                      # [linux]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk           # [osx]

pin_run_as_build:
  arpack:
    max_pin: x.x.x
  boost:
    max_pin: x.x.x
  boost-cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  cairo:
    max_pin: x.x
  cudnn:
    max_pin: x
    min_pin: x.x
  curl:
    max_pin: x
  dbus:
    max_pin: x
  expat:
    max_pin: x.x
  ffmpeg:
    max_pin: x.x
  fftw:
    max_pin: x
  flann:
    max_pin: x.x.x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  gdal:
    max_pin: x.x
  geotiff:
    max_pin: x.x.x
  glew:
    max_pin: x.x
  glpk:
    max_pin: x.x
  gmp:
    max_pin: x
  graphviz:
    max_pin: x
  harfbuzz:
    max_pin: x
  hdf4:
    max_pin: x.x
  isl:
    max_pin: x.x
  jasper:
    max_pin: x
  jpeg:
    max_pin: x
  libjpeg_turbo:
    max_pin: x
  json-c:
    max_pin: x.x
  jsoncpp:
    max_pin: x.x.x
  kealib:
    max_pin: x.x
  krb5:
    max_pin: x.x
  libblitz:
    max_pin: x.x
  libcurl:
    max_pin: x
  libevent:
    max_pin: x.x.x
  libffi:
    max_pin: x.x
  libgdal:
    max_pin: x.x
  libiconv:
    max_pin: x.x
  libkml:
    max_pin: x.x
  libmatio:
    max_pin: x.x
  libpcap:
    max_pin: x.x
  libpng:
    max_pin: x.x
  librdkafka:
    max_pin: x.x.x
  librsvg:
    max_pin: x
  libsvm:
    max_pin: x.x
  libtiff:
    max_pin: x
  libxml2:
    max_pin: x.x
  libuuid:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  lzo:
    max_pin: x
  metis:
    max_pin: x.x
  mkl:
    max_pin: x
  mpfr:
    max_pin: x
  ncurses:
    max_pin: x.x
  netcdf-cxx4:
    max_pin: x.x
  netcdf-fortran:
    max_pin: x.x
  nettle:
    max_pin: x.x
  nlopt:
    max_pin: x.x.x
  nss:
    max_pin: x
  nspr:
    max_pin: x
  occt:
    max_pin: x.x
  openturns:
    max_pin: x.x
  openjpeg:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  pango:
    max_pin: x.x
  perl:
    max_pin: x.x.x
  poppler:
    max_pin: x.x
  qt:
    max_pin: x.x
  readline:
    max_pin: x
  r-base:
    max_pin: x.x
    min_pin: x.x
  sox:
    max_pin: x.x.x
  sqlite:
    max_pin: x
  tk:
    max_pin: x.x
  tiledb:
    max_pin: x.x
  vlfeat:
    max_pin: x.x.x
  vtk:
    max_pin: x.x.x
  xz:
    max_pin: x.x
  zeromq:
    max_pin: x.x  # [not win]
    max_pin: x.x.x  # [win]
  zlib:
    max_pin: x.x

# Pinning packages

# blas
libblas:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
libcblas:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
liblapack:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
liblapacke:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

abseil_cpp:
  - '20200225.2'
alsa_lib:
  - 1.2.3
arb:
  - '2.18'
arpack:
  - 3.7
arrow_cpp:
  - 1.0.1
aws_c_common:
  - 0.4.59
aws_c_event_stream:
  - 0.1.6
aws_checksums:
  - 0.1.10
aws_sdk_cpp:
  - 1.8.70
boost:
  - 1.72.0  # [not (osx and arm64)]
  - 1.74.0  # [osx and arm64]
boost_cpp:
  - 1.72.0  # [not (osx and arm64)]
  - 1.74.0  # [osx and arm64]
bzip2:
  - 1
cairo:
  - 1.16
cfitsio:
  - 3.470
cudnn:
  - 7.6.5
curl:
  - 7
dbus:
  - 1
expat:
  - 2.2
ffmpeg:
  - '4.3'
fftw:
  - 3
flann:
  - 1.9.1
fmt:
  - '7'
fontconfig:
  - 2.13
freetype:
  - 2
gf2x:
  - '1.3'
gdk_pixbuf:
  - 2
gnuradio_core:
  - 3.8.2
gsl:
  - 2.6
gstreamer:
  - 1.14.4
gst_plugins_base:
  - 1.14.4
gdal:
  - 3.0
geos:
  - 3.8.1
geotiff:
  - '1.6'
gflags:
  - 2.2
giflib:
  - 5.2
glew:
  - 2.1
glib:
  - 2.58  # [not (osx and arm64)]
  # Can't update to 2.66 on `osx and x86_64` yet because that requires a newer macOS version than 10.9
  - 2.66  # [osx and arm64]
glog:
  - 0.4.0
glpk:
  - 4.65
gmp:
  - 6
google_cloud_cpp:
  - '1.21'
google_cloud_cpp_common:
  - 0.25.0
googleapis_cpp:
  - '0.10'
graphviz:
  - 2.38  # [win]
  - 2.40  # [not win]
grpc_cpp:
  - '1.33'
harfbuzz:
  - 2
hdf4:
  - 4.2
hdf5:
  - 1.10.5
icu:
  - 67
isl:
  - '0.22'
jasper:
  # the first windows build of jasper was 2.0.14
  - 1  # [not win]
  - 2  # [win]
jpeg:
  - 9
libjpeg_turbo:
  - 2
json_c:
  - 0.13
jsoncpp:
  - 1.8.4
kealib:
  - 1.4
krb5:
  - 1.17.1
libarchive:
  - 3.3
libblitz:
  - 0.10
libcurl:
  - 7
libcrc32c:
  - 1.1
libdap4:
  - 3.20.2
libevent:
  - 2.1.10
libffi:
  - 3.2
libgdal:
  - 3.0
libiconv:
  - 1.16
libkml:
  - 1.3
libmatio:
  - 1.5
libmicrohttpd:
  - 0.9
libnetcdf:
  - 4.7.4
libpcap:
  - '1.9'
libpng:
  - 1.6
libprotobuf:
  - 3.12
librdkafka:
  - '1.4'
librsvg:
  - 2
libsecret:
  - 0.18
libspatialindex:
  - 1.9.3
libssh2:
  - 1
libsvm:
  - 3.21
libtiff:
  - 4.1.0
libunwind:
  - 1
libv8:
  - 8.9.15
libwebp:
  - 1.1
libwebp_base:
  - 1.1
libxml2:
  - 2.9
libuuid:
  - 2.32.1
log4cxx:
  - 0.11.0
lz4_c:
  - 1.9.2
lzo:
  - 2
metis:
  - 5.1
mimalloc:
  - 1.6.3
mkl:
  - 2019
mpich:
  - 3.3
mpfr:
  - 4
mumps_mpi:
  - 5.2
mumps_seq:
  - 5.2
nccl:
  - 2.7.8.1
ncurses:
  - 6.2
netcdf_cxx4:
  - 4.3
netcdf_fortran:
  - 4.5
nettle:
  - 3.4
nss:
  - 3
nspr:
  - 4
nlopt:
  - 2.6.*
ntl:
  - '11.4.3'
# we build for the oldest version possible of numpy for forward compatibility
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.16   # [not (osx and arm64)]
  - 1.16   # [not (osx and arm64)]
  - 1.16   # [not (osx and arm64)]
  - 1.19   # [osx and arm64]
occt:
  - 7.4
openblas:
  - 0.3.*
openexr:
  - 2.5
openjpeg:
  - 2.3
openmpi:
  - 4.0
openssl:
  - 1.1.1
openturns:
  - '1.15'
orc:
  - 1.6.5
pango:
  - 1.42
pari:
  - 2.11
perl:
  - 5.26.2
petsc:
  - '3.13'
petsc4py:
  - '3.13'
slepc:
  - '3.13'
slepc4py:
  - '3.13'
pixman:
  - 0
poco:
  - 1.10.1
poppler:
  - '0.89'
proj:
  - 7.1.1
python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.6.* *_cpython    # [not (osx and arm64)]
  - 3.7.* *_cpython    # [not (osx and arm64)]
  - 3.8.* *_cpython
python_impl:
  # part of a zip_keys: python, python_impl, numpy
  - cpython   # [not (osx and arm64)]
  - cpython   # [not (osx and arm64)]
  - cpython
qt:
  - 5.12
re2:
  - 2020.11.01
readline:
  - 8.0
rocksdb:
  - "6.10"
root_base:
  - '6.22'
ruby:
  - 2.5
  - 2.6
r_base:
  - 3.6
  - 4.0
scotch:
  - 6.0.9
ptscotch:
  - 6.0.9
singular:
  - 4.1.2
snappy:
  - 1
soapysdr:
  - 0.7
sox:
  - 14.4.2
sqlite:
  - 3
suitesparse:
  - 5.6                # [not win]
  - 5.4                # [win]
tk:
  - 8.6                # [not ppc64le]
tiledb:
  - '2.1'
uhd:
  - 3.15.0
vc:                    # [win]
  - 14                 # [win]
vlfeat:
  - 0.9.20
vtk:
  - 8.2.0
x264:
  - 1!152.*
xerces_c:
  - 3.2
xrootd:
  - '5'
xz:
  - 5.2
zeromq:
  - 4.3.2
zlib:
  - 1.2
zstd:
  - 1.4
