{% set name = "GQCP" %}
{% set version = "0.2.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/GQCG/GQCP.git
    git_tag: devops/conda
requirements:
    build:
      - git
      - make
      - cmake {{ cmake }}
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - llvm-openmp               # [osx]
      - openmp                    # [linux]
      - intel-openmp      
      - eigen {{ eigen }}
      - mkl-include {{ mkl_include }}
      - mkl-static {{ mkl_static }}
      - pybind11 {{ pybind11 }}
    host:
      - boost-cpp {{ boost_cpp }}
      - blas
      - {{ pin_compatible('mkl') }}
      - python {{ python }}
      - benchmark
      - mkl {{ mkl }}
      - libint {{ libint }}
      - spectra {{ spectra }}
      - cint {{ cint }}
    run:
      - {{ pin_compatible('numpy') }}
      - python {{ python }}
test:
  commands:
    - test -f ${PREFIX}/lib/libgqcp$SHLIB_EXT
    - test -f ${PREFIX}/include/gqcp/gqcp.hpp
about:
    home: https://github.com/GQCG/GQCP.git
    license: GNU Lesser General Public License v3.0
    license_file: LICENSE
    summary: 'The Ghent Quantum Chemistry Package for electronic structure calculations.'
