{% set name = "GQCP" %}
{% set version = "0.2.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/GQCG/GQCP.git
    git_tag: develop
requirements:
    build:
      - benchmark
      - cmake
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - git
      - make
    host:
      - blas
      - boost-cpp
      - cint
      - eigen
      - intel-openmp
      - mkl-include
      - mkl-static
      - numpy
      - libint
      - llvm-openmp               # [osx]
      - numpy 
      - openmp                    # [linux]
      - pybind11 
      - python
    run:
      - blas
      - boost-cpp
      - cint
      - eigen
      - intel-openmp
      - mkl-include
      - mkl-static
      - numpy
      - libint
      - llvm-openmp               # [osx]
      - numpy
      - intel-openmp              # [linux]
      - python
test:
  commands:
    - test -f ${PREFIX}/lib/libgqcp$SHLIB_EXT
    - test -f ${PREFIX}/include/gqcp/gqcp.hpp
about:
    home: https://github.com/GQCG/GQCP.git
    license: GNU Lesser General Public License v3.0
    license_file: LICENSE
    summary: 'The Ghent Quantum Chemistry Package for electronic structure calculations.'
