# CMake generated Testfile for 
# Source directory: /Users/daria/ugent/gqcp/gqcp/tests
# Build directory: /Users/daria/ugent/gqcp/gqcp/gqcp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TransformationMatrix_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/TransformationMatrix_test")
set_tests_properties(TransformationMatrix_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(LibintInterfacer_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/LibintInterfacer_test")
set_tests_properties(LibintInterfacer_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(IntegralCalculator_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/IntegralCalculator_test")
set_tests_properties(IntegralCalculator_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(CartesianExponents_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/CartesianExponents_test")
set_tests_properties(CartesianExponents_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(CartesianGTO_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/CartesianGTO_test")
set_tests_properties(CartesianGTO_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(GTOShell_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/GTOShell_test")
set_tests_properties(GTOShell_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(ScalarBasis_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/ScalarBasis_test")
set_tests_properties(ScalarBasis_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(ShellSet_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/ShellSet_test")
set_tests_properties(ShellSet_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(GSpinorBasis_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/GSpinorBasis_test")
set_tests_properties(GSpinorBasis_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(JacobiRotationParameters_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/JacobiRotationParameters_test")
set_tests_properties(JacobiRotationParameters_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(OrbitalRotationGenerators_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/OrbitalRotationGenerators_test")
set_tests_properties(OrbitalRotationGenerators_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(RSpinorBasis_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/RSpinorBasis_test")
set_tests_properties(RSpinorBasis_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SimpleSpinorBasis_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SimpleSpinorBasis_test")
set_tests_properties(SimpleSpinorBasis_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(USpinorBasis_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/USpinorBasis_test")
set_tests_properties(USpinorBasis_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(ScalarFunction_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/ScalarFunction_test")
set_tests_properties(ScalarFunction_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(Eigenpair_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/Eigenpair_test")
set_tests_properties(Eigenpair_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(EigenproblemSolver_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/EigenproblemSolver_test")
set_tests_properties(EigenproblemSolver_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(IterativeIdentitiesHessianModifier_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/IterativeIdentitiesHessianModifier_test")
set_tests_properties(IterativeIdentitiesHessianModifier_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(Minimizer_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/Minimizer_test")
set_tests_properties(Minimizer_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(NonLinearEquationSolver_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/NonLinearEquationSolver_test")
set_tests_properties(NonLinearEquationSolver_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(BlockMatrix_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/BlockMatrix_test")
set_tests_properties(BlockMatrix_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(BlockRankFourTensor_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/BlockRankFourTensor_test")
set_tests_properties(BlockRankFourTensor_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(Matrix_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/Matrix_test")
set_tests_properties(Matrix_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(QCMatrix_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/QCMatrix_test")
set_tests_properties(QCMatrix_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(QCRankFourTensor_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/QCRankFourTensor_test")
set_tests_properties(QCRankFourTensor_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SquareMatrix_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SquareMatrix_test")
set_tests_properties(SquareMatrix_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SquareRankFourTensor_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SquareRankFourTensor_test")
set_tests_properties(SquareRankFourTensor_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(Tensor_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/Tensor_test")
set_tests_properties(Tensor_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(elements_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/elements_test")
set_tests_properties(elements_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(Molecule_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/Molecule_test")
set_tests_properties(Molecule_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(NuclearFramework_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/NuclearFramework_test")
set_tests_properties(NuclearFramework_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(Nucleus_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/Nucleus_test")
set_tests_properties(Nucleus_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SpinResolvedFrozenONVBasis_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SpinResolvedFrozenONVBasis_test")
set_tests_properties(SpinResolvedFrozenONVBasis_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SpinResolvedONVBasis_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SpinResolvedONVBasis_test")
set_tests_properties(SpinResolvedONVBasis_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SpinResolvedSelectedONVBasis_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SpinResolvedSelectedONVBasis_test")
set_tests_properties(SpinResolvedSelectedONVBasis_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SpinUnresolvedFrozenONVBasis_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SpinUnresolvedFrozenONVBasis_test")
set_tests_properties(SpinUnresolvedFrozenONVBasis_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SpinUnresolvedONV_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SpinUnresolvedONV_test")
set_tests_properties(SpinUnresolvedONV_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SpinUnresolvedONVBasis_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SpinUnresolvedONVBasis_test")
set_tests_properties(SpinUnresolvedONVBasis_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(NuclearDipoleOperator_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/NuclearDipoleOperator_test")
set_tests_properties(NuclearDipoleOperator_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(NuclearRepulsionOperator_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/NuclearRepulsionOperator_test")
set_tests_properties(NuclearRepulsionOperator_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SQHamiltonian_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SQHamiltonian_test")
set_tests_properties(SQHamiltonian_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SQOneElectronOperator_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SQOneElectronOperator_test")
set_tests_properties(SQOneElectronOperator_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SQTwoElectronOperator_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SQTwoElectronOperator_test")
set_tests_properties(SQTwoElectronOperator_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(USQHamiltonian_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/USQHamiltonian_test")
set_tests_properties(USQHamiltonian_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(USQOneElectronOperator_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/USQOneElectronOperator_test")
set_tests_properties(USQOneElectronOperator_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(USQTwoElectronOperator_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/USQTwoElectronOperator_test")
set_tests_properties(USQTwoElectronOperator_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(expectation_values_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/expectation_values_test")
set_tests_properties(expectation_values_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(properties_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/properties_test")
set_tests_properties(properties_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(DOCIRDMBuilder_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/DOCIRDMBuilder_test")
set_tests_properties(DOCIRDMBuilder_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(FCIRDMBuilder_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/FCIRDMBuilder_test")
set_tests_properties(FCIRDMBuilder_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(FrozenCoreFCIRDMBuilder_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/FrozenCoreFCIRDMBuilder_test")
set_tests_properties(FrozenCoreFCIRDMBuilder_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(OneRDM_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/OneRDM_test")
set_tests_properties(OneRDM_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SelectedRDMBuilder_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SelectedRDMBuilder_test")
set_tests_properties(SelectedRDMBuilder_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SpinUnresolvedFCIRDMBuilder_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SpinUnresolvedFCIRDMBuilder_test")
set_tests_properties(SpinUnresolvedFCIRDMBuilder_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(TwoRDM_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/TwoRDM_test")
set_tests_properties(TwoRDM_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(AtomicDecompositionParameters_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/AtomicDecompositionParameters_test")
set_tests_properties(AtomicDecompositionParameters_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(constrained_RHF_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/constrained_RHF_test")
set_tests_properties(constrained_RHF_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(DOCI_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/DOCI_test")
set_tests_properties(DOCI_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(DOCINewtonOrbitalOptimizer_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/DOCINewtonOrbitalOptimizer_test")
set_tests_properties(DOCINewtonOrbitalOptimizer_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(FCI_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/FCI_test")
set_tests_properties(FCI_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(Hubbard_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/Hubbard_test")
set_tests_properties(Hubbard_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(DOCI_builder_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/DOCI_builder_test")
set_tests_properties(DOCI_builder_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(FCI_builder_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/FCI_builder_test")
set_tests_properties(FCI_builder_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(FrozenCoreFCI_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/FrozenCoreFCI_test")
set_tests_properties(FrozenCoreFCI_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(Hubbard_builder_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/Hubbard_builder_test")
set_tests_properties(Hubbard_builder_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(SelectedCI_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/SelectedCI_test")
set_tests_properties(SelectedCI_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(AP1roGJacobiOrbitalOptimizer_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/AP1roGJacobiOrbitalOptimizer_test")
set_tests_properties(AP1roGJacobiOrbitalOptimizer_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(AP1roGLagrangianNewtonOrbitalOptimizer_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/AP1roGLagrangianNewtonOrbitalOptimizer_test")
set_tests_properties(AP1roGLagrangianNewtonOrbitalOptimizer_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(QCMethod_AP1roG_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/QCMethod_AP1roG_test")
set_tests_properties(QCMethod_AP1roG_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(QCMethod_vAP1roG_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/QCMethod_vAP1roG_test")
set_tests_properties(QCMethod_vAP1roG_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(QCMethod_RHF_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/QCMethod_RHF_test")
set_tests_properties(QCMethod_RHF_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(RHFSCFEnvironment_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/RHFSCFEnvironment_test")
set_tests_properties(RHFSCFEnvironment_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(ERJacobiLocalizer_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/ERJacobiLocalizer_test")
set_tests_properties(ERJacobiLocalizer_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(ERNewtonLocalizer_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/ERNewtonLocalizer_test")
set_tests_properties(ERNewtonLocalizer_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(RMP2_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/RMP2_test")
set_tests_properties(RMP2_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(CCD0_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/CCD0_test")
set_tests_properties(CCD0_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(LinearExpansion_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/LinearExpansion_test")
set_tests_properties(LinearExpansion_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(AP1roGGeminalCoefficients_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/AP1roGGeminalCoefficients_test")
set_tests_properties(AP1roGGeminalCoefficients_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(APIGGeminalCoefficients_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/APIGGeminalCoefficients_test")
set_tests_properties(APIGGeminalCoefficients_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(RHF_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/RHF_test")
set_tests_properties(RHF_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(linalg_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/linalg_test")
set_tests_properties(linalg_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(miscellaneous_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/miscellaneous_test")
set_tests_properties(miscellaneous_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
add_test(units_test "/Users/daria/ugent/gqcp/gqcp/gqcp/tests/units_test")
set_tests_properties(units_test PROPERTIES  WORKING_DIRECTORY "/Users/daria/ugent/gqcp/gqcp/gqcp/tests" _BACKTRACE_TRIPLES "/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;29;add_test;/Users/daria/ugent/gqcp/gqcp/tests/CMakeLists.txt;0;")
subdirs("Basis")
subdirs("Mathematical")
subdirs("Molecule")
subdirs("ONVBasis")
subdirs("Operator")
subdirs("Processing")
subdirs("QCMethod")
subdirs("QCModel")
subdirs("Utilities")
