// This file is part of GQCG-GQCP.
//
// Copyright (C) 2017-2020  the GQCG developers
//
// GQCG-GQCP is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// GQCG-GQCP is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with GQCG-GQCP.  If not, see <http://www.gnu.org/licenses/>.

#include "QCMethod/CC/CCSDSolver.hpp"
#include "Utilities/complex.hpp"

#include <pybind11/pybind11.h>


namespace gqcpy {


// Provide some shortcuts for frequent namespaces.
namespace py = pybind11;
using namespace GQCP;


/**
 *  Add Python bindings for some APIs related to `CCSDSolver`.
 * 
 *  @tparam Class               The type of the Pybind11 `class_` (generated by the compiler).
 *  
 *  @param py_class             The Pybind11 `class_` that should obtain APIs related to `CCSDSolver`.
 */
template <typename Class>
void bindCCSDSolverInterface(Class& py_class) {

    // The C++ type corresponding to the Python class.
    using Type = typename Class::type;

    using Scalar = typename Type::Scalar;


    py_class
        .def_static(
            "Plain",
            [](const double threshold, const size_t maximum_number_of_iterations) {
                return CCSDSolver<Scalar>::Plain(threshold, maximum_number_of_iterations);
            },
            py::arg("threshold") = 1.0e-08,
            py::arg("maximum_number_of_iterations") = 128,
            "Return a plain CCSD solver that uses the norm of the difference of consecutive amplitudes as a convergence criterion.");
}


/**
 *  Register multiple templated `CCSDSolver` to the gqcpy module and expose parts of their C++ interfaces to Python.
 * 
 *  @param module           The Pybind11 module in which the classes should be registered.
 */
void bindCCSDSolver(py::module& module) {

    // Real-valued Python bindings.
    py::class_<CCSDSolver<double>> py_CCSDSolver_d {module, "CCSDSolver_d", "A factory class that can construct CCSD solvers for real-valued calculations."};
    bindCCSDSolverInterface(py_CCSDSolver_d);

    // Complex-valued Python bindings.
    py::class_<CCSDSolver<complex>> py_CCSDSolver_cd {module, "CCSDSolver_cd", "A factory class that can construct CCSD solvers for complex-valued calculations."};
    bindCCSDSolverInterface(py_CCSDSolver_cd);
}


}  // namespace gqcpy
