// This file is part of GQCG-GQCP.
//
// Copyright (C) 2017-2020  the GQCG developers
//
// GQCG-GQCP is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// GQCG-GQCP is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with GQCG-GQCP.  If not, see <http://www.gnu.org/licenses/>.

#include "Mathematical/Algorithm/IterativeAlgorithm.hpp"
#include "QCMethod/HF/RHF/DiagonalRHFFockMatrixObjective.hpp"
#include "QCMethod/HF/RHF/RHF.hpp"
#include "QCMethod/HF/RHF/RHFSCFSolver.hpp"
#include "Utilities/aliases.hpp"

#include <pybind11/pybind11.h>


namespace gqcpy {


// Provide some shortcuts for frequent namespaces.
namespace py = pybind11;
using namespace GQCP;


/**
 *  Add Python bindings for some APIs related to `QCMethod::RHF`.
 * 
 *  @tparam Class               The type of the Pybind11 `class_` (generated by the compiler).
 *  
 *  @param py_class             The Pybind11 `class_` that should obtain APIs related to `QCMethod::RHF`.
 */
template <typename Class>
void bindQCMethodRHFInterface(Class& py_class) {

    // The C++ type corresponding to the Python class.
    using Type = typename Class::type;
    using Scalar = typename Type::Scalar;


    py_class

        /*
         *  MARK: Public methods
         */

        .def_static(
            "optimize",
            [](const DiagonalRHFFockMatrixObjective<Scalar>& objective, IterativeAlgorithm<RHFSCFEnvironment<Scalar>>& solver, RHFSCFEnvironment<Scalar>& environment) {
                return QCMethod::RHF<Scalar>().optimize(objective, solver, environment);
            },
            "Optimize the RHF wave function model: find the parameters satisfy the given objective.");
}


/**
 *  Add Python bindings for RHF QCMethods.
 */
void bindQCMethodsRHF(py::module& module) {

    // Provide Python bindings for real-valued RHF.
    py::class_<QCMethod::RHF<double>> py_QCMethodRHF_d {module, "RHF_d", "The (real) restricted Hartree-Fock quantum chemical method."};

    bindQCMethodRHFInterface(py_QCMethodRHF_d);


    // Provide Python bindings for complex-valued RHF.
    py::class_<QCMethod::RHF<complex>> py_QCMethodRHF_cd {module, "RHF_cd", "The (complex) restricted Hartree-Fock quantum chemical method."};

    bindQCMethodRHFInterface(py_QCMethodRHF_cd);
}


}  // namespace gqcpy
