@startuml

namespace gqcg {

    class GQCG::Atom {
        __ public members __
            + unsigned atomic_number
            + double x, y, z
    }

    GQCG::Molecule o--> GQCG::Atom
    class GQCG::Molecule {
        __ private members __
            - const std::vector<GQCG::Atom> atoms
            - size_t N
        __ private methods __
            - std::vector<GQCG::Atom> parseXYZFile(std::string filename) const
        == constructors ==
            **Molecule**(std::string xyz_filename)
            **Molecule**(std::string xyz_filename, int molecular_charge)
            **Molecule**(const std::vector<GQCG::Atom>& atoms)
            **Molecule**(const std::vector<GQCG::Atom>& atoms, int molecular_charge)
        __ public methods __
            + site_t **get_N** () const

            + size_t **numberOfAtoms**() const
            + size_t **calculateTotalNucleicCharge**() const
            + double **calculateInternuclearDistance**(size_t index1, size_t index2) const
            + double **calculateInternuclearRepulsionEnergy**() const
    }

    abstract class IntegralCalculator
    class Basis {
        // Change the Name to integral evaluation?
        // hamiltonian one particle evaluation?
        // up for debate
        == constructors ==
           **Basis**(IntegralCalculator, string basisSet, Molecule)
           **Basis**(h_matrix, g_tensor, s_matrix)
           **Basis**(filename)
        __public__
           +transform
   }

    abstract class QCM {
        __public__
        +get_energy
        +get_wavefunction
        __private__
        -param

    }

    abstract AllNumoptSolverInterface

    gqcg.Basis ..> gqcg.IntegralCalculator
    gqcg.Basis ..> gqcg.Molecule

    gqcg.QCM ..> gqcg.Basis



}

namespace libwint {
    class Libwint
}

libwint.Libwint --|> gqcg.IntegralCalculator

namespace oo {
    abstract class OO {
        ==constructor==
         **OO**(QCM)
    }
    class OOjacobi {

    }
}


oo.OO o--> gqcg.QCM
oo.OO o--> gqcg.Basis
oo.OOjacobi --|> oo.OO

namespace ci {
    abstract class BaseCI
    class DOCI
    class FCI
    class OODOCI
    class SelectedCI
}

ci.BaseCI --|> gqcg.QCM
ci.OODOCI --|> oo.OO
ci.DOCI --|> ci.BaseCI
ci.FCI --|> ci.BaseCI
ci.SelectedCI --|> ci.BaseCI
ci.BaseCI o--> gqcg.AllNumoptSolverInterface

namespace rdm {
}
namespace constraints {
}

namespace hf {
}


@enduml

