name: Build and test

on: 
  pull_request:
    paths:
      - '.github/workflows/build-and-test.yml'
      - '**.hpp'
      - '**.cpp'
      - '**.cmake'
      - '**CMakeLists.txt'
      - 'cmake/**'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    container:
      image: gqcg/gqcp-dev:latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build, test and install
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=TRUE -DBUILD_BENCHMARKS=TRUE -DBUILD_PYTHON_BINDINGS=TRUE -DCMAKE_INSTALL_PREFIX=/usr/local/miniconda3 -DCMAKE_PREFIX_PATH=/usr/local/miniconda3 -DPYTHON_EXECUTABLE=/usr/local/miniconda3/bin/python3 -DPYTHON_LIBRARY=/usr/local/miniconda3/lib/libpython3.8m.a
        make -j2 VERBOSE=1 && env CTEST_OUTPUT_ON_FAILURE=1 make test && make install
    - name: Link test
      run: |
        cd tools/link-test
        mkdir build && cd build
        cmake .. -DCMAKE_MODULE_PATH=/usr/local/miniconda3/cmake
        make -j2 VERBOSE=1 && ./link
        