name: Conda CI/CD

on:
  push:
    paths:
    - '.github/workflows/ci-cd-conda.yml'
    - 'conda/**'
    - 'workflows/ci-cd-conda.yml'
    - '**.hpp'
    - '**.cpp'
    - '**.cmake'
    - '**CMakeLists.txt'
    - 'cmake/**'
    branches:
      - develop
  pull_request:
    paths:
    - '.github/workflows/ci-cd-conda.yml'
    - 'conda/**'
    - 'workflows/ci-cd-conda.yml'
    - '**.hpp'
    - '**.cpp'
    - '**.cmake'
    - '**CMakeLists.txt'
    - 'cmake/**'

jobs:
  conda-ci-cd:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
        py: [3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
      - name: Python ${{ matrix.py }} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.py }}
          conda-channels: anaconda, conda-forge, intel
      - name: Download MacOSX 10.9 SDK as conda-build dependency
        if: matrix.os == 'macos-12'
        run: |
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz
          wget https://github.com/alexey-lysiuk/macos-sdk/releases/download/12.3/MacOSX12.3.tar.xz
          sudo mkdir /opt/MacOSX12.3.sdk
          sudo tar -xf MacOSX12.3.tar.xz -C /opt
          ls -hal /opt/MacOSX12.3.sdk
      - name: Build conda package
        if: github.event_name == 'pull_request'
        run: |
          GIT_BRANCH=${{ github.head_ref }}
          sed -i -e "s|develop|$GIT_BRANCH|g" conda/meta.yaml
          conda create -n packaging -c conda-forge python=${{ matrix.py }} conda-build anaconda-client conda-verify
          source activate packaging
          conda config --set anaconda_upload no
          conda-build -c gqcg -c conda-forge -c intel conda --user ${{ secrets.ANACONDA_USER }} --token ${{ secrets.ANACONDA_TOKEN }} --variants "{python: [${{ matrix.py }}] }"
      - name: Deploy conda package
        if: github.event_name == 'push'
        run: |
          conda create -n packaging -c conda-forge python=${{ matrix.py }} conda-build anaconda-client conda-verify
          source activate packaging
          conda config --set anaconda_upload yes
          conda-build -c gqcg -c conda-forge -c intel conda --user ${{ secrets.ANACONDA_USER }} --token ${{ secrets.ANACONDA_TOKEN }} --variants "{python: [${{ matrix.py }}] }"

