name: Conda build

on:
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.cmake'
      - '**CMakeLists.txt'
      - 'cmake/**'
      - 'conda/**'
    branches:
      - 'release/**'
      - 'master'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        py: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
      - uses: actions/checkout@v2
      - name: Download conda (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
      - name: Download conda (macOS)
        if: matrix.os == 'macos-latest'
        run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/miniconda.sh
      - name: Install conda
        run: |     
          bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
          echo "::add-path::$HOME/miniconda/bin"
      - name: Download MacOSX 10.9 SDK as conda-build dependency
        if: matrix.os == 'macos-latest'
        run: |
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz
          sudo mkdir /opt/MacOSX10.9.sdk
          sudo tar -xf MacOSX10.9.sdk.tar.xz -C /opt
          ls -hal /opt/MacOSX10.9.sdk
      - name: Deploy conda package
        run: |
          conda create -n packaging -c conda-forge conda-build anaconda-client conda-verify
          source activate packaging
          conda-build -c gqcg -c conda-forge -c intel conda --variants "{python: [${{ matrix.py }}] }"
          anaconda logout
