name: GQCP-dev Docker

on:
  push:
    paths:
      - '.github/workflows/docker-gqcp-dev-deploy.yml'
      - 'docker/GQCP-dev.docker'
    branches:
      - 'develop'
  pull_request:
    paths:
      - '.github/workflows/docker-gqcp-dev-deploy.yml'
      - 'docker/GQCP-dev.docker'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build 
      uses: docker/build-push-action@v2
      if: github.event_name == 'pull_request'
      with:
        context: .
        file: docker/GQCP-dev.docker
        push: false
        tags: gqcg/gqcp-dev:latest
    - name: Build and deploy
      uses: docker/build-push-action@v2
      if: github.event_name == 'push'
      with:
        context: .
        file: docker/GQCP-dev.docker
        push: true
        tags: gqcg/gqcp-dev:latest
    - name: Set up Singularity
      uses: eWaterCycle/setup-singularity@v5
      with: 
         singularity-version: 3.6.1
    - name: Build Singularity image
      run: singularity build gqcp-dev.sif docker://gqcg/gqcp-dev
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
         name: gqcp-dev.sif
         path: gqcp-dev.sif
         retention-days: 5
