name: Docker local image

on:
  pull_request:
    paths:
      - '.github/workflows/docker-gqcp-local-image.yml'
      - 'Dockerfile'
      - '**.hpp'
      - '**.cpp'
      - '**.cmake'
      - '**CMakeLists.txt'
      - 'cmake/**'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build local image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        tags: gqcg/gqcp:local
        outputs: type=docker,dest=gqcp.tar
    - name: Set up Singularity
      uses: eWaterCycle/setup-singularity@v5
      with: 
        singularity-version: 3.6.1
    - name: Build Singularity image
      run: singularity build gqcp.sif gqcp.tar
    - name: Upload Docker artifact
      uses: actions/upload-artifact@v2
      with:
        name: gqcp.tar
        path: gqcp.tar
    - name: Upload Singularity artifact
      uses: actions/upload-artifact@v2
      with:
        name: gqcp.sif
        path: gqcp.sif
