name: GQCP Docker

on:
  push:
    paths:
      - '.github/workflows/docker-gqcp-deploy.yml'
      - 'docker/GQCP.docker'
      - '**.hpp'
      - '**.cpp'
      - '**.cmake'
      - '**CMakeLists.txt'
      - 'cmake/**'
    branches:
      - 'develop'
  pull_request:
    paths:
      - '.github/workflows/docker-gqcp-deploy.yml'
      - 'docker/GQCP.docker'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build 
      uses: docker/build-push-action@v2
      if: github.event_name == 'pull_request'
      with:
        context: .
        file: docker/GQCP.docker
        push: false
        tags: gqcg/gqcp:latest
    - name: Build and deploy
      uses: docker/build-push-action@v2
      if: github.event_name == 'push'
      with:
        context: .
        file: docker/GQCP.docker
        push: true
        tags: gqcg/gqcp:latest
