name: GQCP

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7' 
    - uses: actions/checkout@v1

    - name: Install Miniconda
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
        bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
        echo "::add-path::$HOME/miniconda/bin"

    - name: Install some GQCP dependencies through Conda
      run: |
        conda install -c conda-forge cmake=3.13 boost-cpp=1.69.0 eigen blas mkl pybind11 benchmark numpy;
        conda install -c gqcg libint spectra cint;
        conda install -c intel mkl-include mkl-static intel-openmp;

    # Build & test the library 
    - name: Build GQCP and run tests
      run: |
        export LIBINT_DATA_PATH=$HOME/miniconda/share/libint/2.3.1/basis
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=TRUE -DBUILD_BENCHMARKS=TRUE -DBUILD_PYTHON_BINDINGS=TRUE -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_PREFIX_PATH=$HOME/miniconda
        make -j2 && env CTEST_OUTPUT_ON_FAILURE=1 make test && sudo make install

    # Run the benchmarks
    - name: Run benchmarks
      run: |
        cd build/gqcp/benchmarks
        ./doci_case --benchmark_counters_tabular=true
        ./doci_matrix --benchmark_counters_tabular=true
        ./doci_matvec --benchmark_counters_tabular=true
        ./fci_matrix --benchmark_counters_tabular=true
        ./fci_matvec --benchmark_counters_tabular=true
        ./hubbard_diagonalization --benchmark_counters_tabular=true
        ./hubbard_matrix --benchmark_counters_tabular=true
        ./hubbard_matvec --benchmark_counters_tabular=true

    # Test if the installed library links properly to external driver
    # This is the final step to verify a successful build: if it does not error it updates the env variables
    - name: Check external linking
      run: |
        cd /tmp
        git clone https://github.com/GQCG/gqcp-link.git
        cd gqcp-link
        mkdir build && cd build
        cmake .. -DCMAKE_PREFIX_PATH=$HOME/miniconda -DGQCP_INSTALL_PREFIX=~/.local -Dgqcp_DIR=/home/runner/.local/cmake
        make -j2 && ./test_driver
