name: Singularity deploy

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up Singularity
      uses: eWaterCycle/setup-singularity@v5
      with: 
        singularity-version: 3.6.1
    - name: Build Singularity image
      run: singularity build gqcp-dev.sif singularity/GQCP-dev.def
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gqcp-dev.sif
        path: gqcp-dev.sif
        retention-days: 5