name: Website

# This workflow is triggered on a pull-request. This is a single event so no brackets are needed.
on: 
  push: 
    branches:
      - develop
    paths:
      - 'site/**'
  pull_request:
    # This workflow will only start if files in site/docs/ or site/website are changed.
    paths: 
    - 'site/**'

jobs:
  build-and-deploy:
    # Configures a build matrix containing multiple operating systems. For each configuration, a copy of the job runs and reports a status.
    runs-on: ${{ matrix.os }}
    # To specify the array of operating systems, we must list them under 'strategy'.
    strategy:
      matrix:
        # This job runs on the latest version of Linux.
        os: [ubuntu-latest]
    steps:
    # The checkout action must be included when your workflow requires a copy of your repository's code.
    - uses: actions/checkout@v2

    # Download and install conda such that we can use it to install the required packages for Docusaurus.
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        
    # Nodejs and Yarn are required packages to run Docusaurus.
    - name: Install Nodejs and Yarn
      run: |
        conda install -c anaconda nodejs
        conda install -c conda-forge yarn

    # Run the Docusaurus installation script.
    - name: Docusaurus installation
      run: |
        cd site/website
        npx docusaurus-init
        yarn

    # Build the site
    - name: Build site using Docusaurus
      run: |
        cd site/website
        yarn run build
    
    # Upload artifact if pull_request
    - name: Archive build
      uses: actions/upload-artifact@v1
      with:
        name: _site
        path: site/website/build/
      if: github.event_name == 'pull_request'
    
    # Deploy the website to GitHub pages.
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/website/build/GQCP
        publish_branch: gh-pages
      if: github.event_name == 'push'
